const sunautoGenrePrompts = {
  pop: [
    "pop",
    "pop rock",
    "pop soul",
    "pop rap",
    "pop punk",
    "indie pop",
    "synthpop",
    "electropop",
    "dance pop",
    "art pop",
    "folk pop",
    "power pop",
    "hyperpop",
    "k-pop",
    "j-pop",
    "britpop",
    "europop",
    "chamber pop",
    "dream pop",
    "sophisti-pop",
    "teen pop",
    "alt-pop",
    "spanish pop",
    "pop italiano",
    "city pop",
    "bubblegum pop",
  ],

  rock: [
    "rock",
    "alternative rock",
    "indie rock",
    "pop rock",
    "folk rock",
    "hard rock",
    "punk rock",
    "psychedelic rock",
    "blues rock",
    "progressive rock",
    "classic rock",
    "art rock",
    "garage rock",
    "soft rock",
    "post-rock",
    "rock and roll",
    "country rock",
    "symphonic rock",
    "noise rock",
    "surf rock",
    "space rock",
    "arena rock",
    "southern rock",
    "glam rock",
    "krautrock",
    "rockabilly",
    "stoner rock",
    "math rock",
    "grunge",
    "post-punk",
  ],

  country: [
    "country",
    "country rock",
    "folk rock",
    "country pop",
    "alt-country",
    "bluegrass",
    "americana",
    "outlaw country",
    "contemporary country",
    "traditional country",
    "country blues",
    "country folk",
    "country gospel",
    "honky tonk",
    "red dirt",
    "western swing",
    "country rap",
    "country soul",
    "bakersfield sound",
    "texas blues",
    "heartland rock",
    "nashville sound",
  ],

  opera: [
    "opera",
    "classical",
    "baroque",
    "romantic",
    "chamber",
    "orchestral",
    "symphony",
    "concerto",
    "opera seria",
    "soprano",
    "symphony",
    "chamber",
    "vocal",
    "nocturnal",
    "motet",
    "cantata",
    "oratorio",
    "operetta",
    "zarzuela",
    "requiem",
    "verismo",
    "grand opera",
  ],

  "hip-hop": [
    "hip hop",
    "rap",
    "trap",
    // "conscious hip hop",
    "boom bap",
    "gangsta",
    // "lo-fi hip hop",
    // "abstract hip hop",
    // "jazz rap",
    // "conscious",
    "gangsta rap",
    "g-funk",
    // "southern hip hop",
    // "west coast hip hop",
    // "east coast hip hop",
    // "drill",
    // "turntablism",
    // "dirty south",
    // "horrorcore",
    // "alternative hip hop",
    // "crunk",
    // "plugg",
    // "phonk",
    // "trap soul",
    // "hyphy",
  ],

  "r&b": [
    "r&b",
    "soul",
    "contemporary r&b",
    "neo-soul",
    "funk",
    "pop soul",
    "motown",
    "quiet storm",
    "smooth soul",
    "blue-eyed soul",
    "deep soul",
    "philly soul",
    "boogie",
    "new jack swing",
    "adult contemporary r&b",
    "soul blues",
    "urban",
    "deep funk",
    "chicago soul",
  ],

  jazz: [
    "jazz",
    "contemporary jazz",
    "smooth jazz",
    "fusion",
    "bebop",
    "big band",
    "cool jazz",
    "modal jazz",
    "free jazz",
    "acid jazz",
    "jazz fusion",
    "vocal jazz",
    "latin jazz",
    "soul jazz",
    "swing",
    "gypsy jazz",
    "nu-jazz",
    "hard bop",
    "avant-garde jazz",
    "jazz-funk",
    "spiritual jazz",
    "chamber jazz",
    "jazz blues",
    "jazz vocal",
    "jazz manouche",
    "jazz-rock",
  ],

  christmas: [
    "christmas",
    "holiday",
    "carol",
    "winter",
    "seasonal",
    "religious",
    "spiritual",
    "choral",
    "orchestral",
    "traditional",
    "relaxation",
    "jingle",
    "hymn",
    "winter synth",
    "advent calendar",
  ],

  choir: [
    "choir",
    "choral",
    "a cappella",
    "vocal",
    "sacred vocal",
    "chœurs sacrés",
    "sacred singers",
    "polyphonic chant",
    "gregorian chant",
    "barbershop",
    "harmony",
    "polyphonic",
    "sacred",
    "vocal group",
    "madrigal",
    "religious",
    "close harmony",
    "vocal music",
    "vocal harmonies",
  ],

  kids: [
    "children",
    "nursery rhyme",
    "educational",
    "lullaby",
    "humorous",
    "playful",
    "cartoon",
    "anime",
    "fantasy",
    "fairy tale",
    "video game",
    "fun",
    "novelty",
    "humor",
    "adventure",
    "vocaloid",
  ],

  swing: [
    "swing",
    "big band",
    "jazz",
    "bebop",
    "cool jazz",
    "dixieland",
    "jump blues",
    "vocal jazz",
    "traditional jazz & new orleans",
    "swing revival",
    "jazz vocal",
    "ballroom",
    "dancehall",
    "crooners",
    "british dance band",
    "ragtime",
  ],

  electronic: [
    "electronic",
    "techno",
    "house",
    "ambient",
    "trance",
    "idm",
    "drum and bass",
    "downtempo",
    "electro",
    "dubstep",
    "breakbeat",
    "glitch",
    "synthwave",
    "trip hop",
    "industrial",
    "vaporwave",
    "experimental electronic",
    "deep house",
    "tech house",
    "ambient techno",
    "ambient trance",
    "drone",
    "electroclash",
    "edm",
    "microhouse",
    "jungle",
    "dub",
    "acid",
  ],

  blues: [
    "blues",
    "blues rock",
    "chicago blues",
    "delta blues",
    "electric blues",
    "soul blues",
    "acoustic blues",
    "country blues",
    "memphis blues",
    "piedmont blues",
    "texas blues",
    "jump blues",
    "electric texas blues",
    "harmonica blues",
    "acoustic chicago blues",
    "traditional acoustic blues",
    "piano blues",
    "modern electric blues",
    "swamp blues",
    "acoustic texas blues",
  ],

  reggae: [
    "reggae",
    "dub",
    "ska",
    "dancehall",
    "roots reggae",
    "reggaeton",
    "ska & rocksteady",
    "rocksteady",
    "dub poetry",
    "reggae rock",
    "lovers rock",
    "reggae gospel",
    "pop reggae",
    "roots",
    "ragga",
    "dancehall reggae",
    "digital dancehall",
    "ska punk",
    "nyahbinghi",
  ],

  metal: [
    "metal",
    "heavy metal",
    "death metal",
    "black metal",
    "progressive metal",
    "doom metal",
    "thrash metal",
    "metalcore",
    "symphonic metal",
    "power metal",
    "alternative metal",
    "folk metal",
    "gothic metal",
    "sludge metal",
    "nu-metal",
    "melodic death metal",
    "technical death metal",
    "deathcore",
    "viking metal",
    "symphonic black metal",
    "industrial metal",
    "mathcore",
    "grindcore",
    "djent",
    "stoner metal",
    "funeral doom metal",
    "nwobhm",
  ],

  folk: [
    "folk",
    "folk rock",
    "indie folk",
    "contemporary folk",
    "psychedelic folk",
    "traditional folk",
    "chamber folk",
    "american folk",
    "english folk",
    "celtic folk",
    "folk punk",
    "folk metal",
    "avant-folk",
    "scottish folk",
    "irish folk",
    "neofolk",
    "nordic folk",
    "appalachian folk",
    "nordic folk rock",
    "norwegian folk",
    "welsh folk",
    "swedish folk",
    "spanish folk",
    "canadian folk",
  ],

  indie: [
    "indie",
    "indie rock",
    "indie pop",
    "indie folk",
    "alternative",
    "alternative rock",
    "indie electronic",
    "art rock",
    "dream pop",
    "shoegaze",
    "post-punk",
    "post-rock",
    "chamber pop",
    "math rock",
    "noise rock",
    "lo-fi",
    "slowcore",
    "jangle pop",
    "bedroom pop",
    "twee pop",
    "baroque pop",
    "indietronica",
    "freak folk",
    "sadcore",
  ],

  funk: [
    "funk",
    "funk / soul",
    "funk rock",
    "jazz-funk",
    "p-funk",
    "funk metal",
    "funk brasileiro",
    "funk nacional",
    "deep funk",
    "funk proibidão",
    "funk soul",
    "funk carioca",
    "funk ostentação",
    "synth funk",
    "funk-pop",
    "latin funk",
    "afro-funk",
    "boogie",
    "future funk",
  ],

  soul: [
    "soul",
    "soul jazz",
    "neo-soul",
    "soul blues",
    "soul pop",
    "blue-eyed soul",
    "deep soul",
    "smooth soul",
    "soul rap",
    "pop soul",
    "philly soul",
    "northern soul",
    "chicago soul",
    "southern soul",
    "psychedelic soul",
    "latin soul",
    "country soul",
    "motown",
  ],

  disco: [
    "disco",
    "nu-disco",
    "italo-disco",
    "euro-disco",
    "space disco",
    "boogie",
    "funk",
    "dance",
    "disco house",
    "disco rap",
    "hi-nrg",
    "electro-disco",
    "latin disco",
    "mutant disco",
    "dance pop",
    "funk soul",
    "eurodance",
    "europop",
    "italodance",
  ],

  punk: [
    "punk",
    "punk rock",
    "hardcore punk",
    "post-punk",
    "pop punk",
    "garage punk",
    "anarcho-punk",
    "crust punk",
    "folk punk",
    "ska punk",
    "horror punk",
    "post-hardcore",
    "noise punk",
    "hardcore",
    "oi",
    "street punk",
    "skate punk",
    "d-beat",
    "queercore",
    "emocore",
    "emo",
    "riot grrrl",
    "screamo",
    "grindcore",
    "crust",
  ],

  gospel: [
    "gospel",
    "christian",
    "religious",
    "spiritual",
    "christian rock",
    "christian rap",
    "contemporary christian",
    "southern gospel",
    "black gospel",
    "praise & worship",
    "christian metal",
    "bluegrass gospel",
    "christian hip hop",
    "christian liturgical",
    "christian r&b",
    "christian pop",
    "traditional black gospel",
    "contemporary gospel",
  ],

  "k-pop": [
    "k-pop",
    "j-pop",
    "k-rock",
    "k-hip-hop",
    "k-r&b",
    "k-indie",
    "k-ballad",
    "pop",
    "dance pop",
    "korean ballad",
    "south korea (대한민국)",
    "south korea",
    "k-idol-hip-hop",
    "k-japanese",
    "visual kei",
    "j-rock",
    "j-rap",
  ],

  edm: [
    "edm",
    "electronic",
    "house",
    "techno",
    "trance",
    "dubstep",
    "drum and bass",
    "electro house",
    "deep house",
    "tech house",
    "progressive house",
    "big room house",
    "tropical house",
    "future house",
    "bass house",
    "future bass",
    "trap [edm]",
    "hardstyle",
    "hardcore edm",
    "happy hardcore",
    "psytrance",
    "goa trance",
    "uplifting trance",
    "progressive trance",
    "techstep",
    "liquid drum and bass",
  ],

  techno: [
    "techno",
    "detroit techno",
    "minimal techno",
    "tech house",
    "acid techno",
    "industrial techno",
    "dub techno",
    "deep tech",
    "hardgroove techno",
    "peak time techno",
    "hard techno",
    "belgian techno",
    "ambient techno",
    "dark techno",
    "melodic techno",
    "deep techno",
    "techno bass",
    "schranz",
  ],

  house: [
    "house",
    "deep house",
    "tech house",
    "electro house",
    "progressive house",
    "acid house",
    "funky house",
    "tropical house",
    "french house",
    "future house",
    "bass house",
    "chicago house",
    "garage house",
    "tribal house",
    "euro house",
    "hard house",
    "afro house",
    "diva house",
    "uk funky",
  ],

  dubstep: [
    "dubstep",
    "brostep",
    "melodic dubstep",
    "chillstep",
    "tearout",
    "future garage",
    "uk bass",
    "riddim",
    "drumstep",
    "wonky",
    "purple sound",
    "trap [edm]",
    "glitch hop",
    "future bass",
    "deathstep",
  ],

  funny: [
    "comedy",
    "humorous",
    "novelty",
    "parody",
    "comedy rock",
    "comedy rap",
    "satire",
    "novelty piano",
    "stand-up comedy",
    "sketch comedy",
    "meme rap",
    "humor",
    "satirical",
    "prank calls",
    "memes",
  ],
};

module.exports = {
  sunautoGenrePrompts,
};
